spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:templates/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kaven
    username: root
    password: 015036
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
